#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC_PJ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SEC_PJ")]
	public partial class lts_sindicatoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertimpresion(impresion instance);
    partial void Updateimpresion(impresion instance);
    partial void Deleteimpresion(impresion instance);
    partial void Insertmaeemp(maeemp instance);
    partial void Updatemaeemp(maeemp instance);
    partial void Deletemaeemp(maeemp instance);
    partial void Insertmaesoc(maesoc instance);
    partial void Updatemaesoc(maesoc instance);
    partial void Deletemaesoc(maesoc instance);
    partial void Insertsoccen(soccen instance);
    partial void Updatesoccen(soccen instance);
    partial void Deletesoccen(soccen instance);
    partial void Insertsocemp(socemp instance);
    partial void Updatesocemp(socemp instance);
    partial void Deletesocemp(socemp instance);
    #endregion
		
		public lts_sindicatoDataContext() : 
				base(global::SEC_PJ.Properties.Settings.Default.SEC_PJConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public lts_sindicatoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_sindicatoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_sindicatoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_sindicatoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<impresion> impresion
		{
			get
			{
				return this.GetTable<impresion>();
			}
		}
		
		public System.Data.Linq.Table<Padron_Capital> Padron_Capital
		{
			get
			{
				return this.GetTable<Padron_Capital>();
			}
		}
		
		public System.Data.Linq.Table<maeemp> maeemp
		{
			get
			{
				return this.GetTable<maeemp>();
			}
		}
		
		public System.Data.Linq.Table<maesoc> maesoc
		{
			get
			{
				return this.GetTable<maesoc>();
			}
		}
		
		public System.Data.Linq.Table<soccen> soccen
		{
			get
			{
				return this.GetTable<soccen>();
			}
		}
		
		public System.Data.Linq.Table<socemp> socemp
		{
			get
			{
				return this.GetTable<socemp>();
			}
		}
		
		public System.Data.Linq.Table<Capital> Capital
		{
			get
			{
				return this.GetTable<Capital>();
			}
		}
		
		public System.Data.Linq.Table<pettazi> pettazi
		{
			get
			{
				return this.GetTable<pettazi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.impresion")]
	public partial class impresion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sexo;
		
		private System.Nullable<int> _clase;
		
		private System.Nullable<int> _numdoc;
		
		private string _apenom;
		
		private string _prof;
		
		private string _domicilio;
		
		private string _tipodoc;
		
		private string _analfabeto;
		
		private string _circuito;
		
		private string _seccion;
		
		private string _fecafi;
		
		private System.Nullable<System.DateTime> _FechaAfil;
		
		private string _apellido;
		
		private string _nombre;
		
		private System.Nullable<int> _nro_calle;
		
		private string _partido;
		
		private string _cuartel;
		
		private string _ciudad;
		
		private string _string2;
		
		private string _dia;
		
		private string _mes;
		
		private string _año;
		
		private string _estadocivil;
		
		private string _lugar;
		
		private string _DM;
		
		private string _reg;
		
		private string _piso;
		
		private string _dpto;
		
		private int _id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnclaseChanging(System.Nullable<int> value);
    partial void OnclaseChanged();
    partial void OnnumdocChanging(System.Nullable<int> value);
    partial void OnnumdocChanged();
    partial void OnapenomChanging(string value);
    partial void OnapenomChanged();
    partial void OnprofChanging(string value);
    partial void OnprofChanged();
    partial void OndomicilioChanging(string value);
    partial void OndomicilioChanged();
    partial void OntipodocChanging(string value);
    partial void OntipodocChanged();
    partial void OnanalfabetoChanging(string value);
    partial void OnanalfabetoChanged();
    partial void OncircuitoChanging(string value);
    partial void OncircuitoChanged();
    partial void OnseccionChanging(string value);
    partial void OnseccionChanged();
    partial void OnfecafiChanging(string value);
    partial void OnfecafiChanged();
    partial void OnFechaAfilChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAfilChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onnro_calleChanging(System.Nullable<int> value);
    partial void Onnro_calleChanged();
    partial void OnpartidoChanging(string value);
    partial void OnpartidoChanged();
    partial void OncuartelChanging(string value);
    partial void OncuartelChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void Onstring2Changing(string value);
    partial void Onstring2Changed();
    partial void OndiaChanging(string value);
    partial void OndiaChanged();
    partial void OnmesChanging(string value);
    partial void OnmesChanged();
    partial void OnañoChanging(string value);
    partial void OnañoChanged();
    partial void OnestadocivilChanging(string value);
    partial void OnestadocivilChanged();
    partial void OnlugarChanging(string value);
    partial void OnlugarChanged();
    partial void OnDMChanging(string value);
    partial void OnDMChanged();
    partial void OnregChanging(string value);
    partial void OnregChanged();
    partial void OnpisoChanging(string value);
    partial void OnpisoChanged();
    partial void OndptoChanging(string value);
    partial void OndptoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public impresion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="NVarChar(1)")]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clase", DbType="Int")]
		public System.Nullable<int> clase
		{
			get
			{
				return this._clase;
			}
			set
			{
				if ((this._clase != value))
				{
					this.OnclaseChanging(value);
					this.SendPropertyChanging();
					this._clase = value;
					this.SendPropertyChanged("clase");
					this.OnclaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numdoc", DbType="Int")]
		public System.Nullable<int> numdoc
		{
			get
			{
				return this._numdoc;
			}
			set
			{
				if ((this._numdoc != value))
				{
					this.OnnumdocChanging(value);
					this.SendPropertyChanging();
					this._numdoc = value;
					this.SendPropertyChanged("numdoc");
					this.OnnumdocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apenom", DbType="NVarChar(255)")]
		public string apenom
		{
			get
			{
				return this._apenom;
			}
			set
			{
				if ((this._apenom != value))
				{
					this.OnapenomChanging(value);
					this.SendPropertyChanging();
					this._apenom = value;
					this.SendPropertyChanged("apenom");
					this.OnapenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prof", DbType="NVarChar(50)")]
		public string prof
		{
			get
			{
				return this._prof;
			}
			set
			{
				if ((this._prof != value))
				{
					this.OnprofChanging(value);
					this.SendPropertyChanging();
					this._prof = value;
					this.SendPropertyChanged("prof");
					this.OnprofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domicilio", DbType="NVarChar(255)")]
		public string domicilio
		{
			get
			{
				return this._domicilio;
			}
			set
			{
				if ((this._domicilio != value))
				{
					this.OndomicilioChanging(value);
					this.SendPropertyChanging();
					this._domicilio = value;
					this.SendPropertyChanged("domicilio");
					this.OndomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipodoc", DbType="NVarChar(10)")]
		public string tipodoc
		{
			get
			{
				return this._tipodoc;
			}
			set
			{
				if ((this._tipodoc != value))
				{
					this.OntipodocChanging(value);
					this.SendPropertyChanging();
					this._tipodoc = value;
					this.SendPropertyChanged("tipodoc");
					this.OntipodocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analfabeto", DbType="NVarChar(50)")]
		public string analfabeto
		{
			get
			{
				return this._analfabeto;
			}
			set
			{
				if ((this._analfabeto != value))
				{
					this.OnanalfabetoChanging(value);
					this.SendPropertyChanging();
					this._analfabeto = value;
					this.SendPropertyChanged("analfabeto");
					this.OnanalfabetoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_circuito", DbType="NVarChar(50)")]
		public string circuito
		{
			get
			{
				return this._circuito;
			}
			set
			{
				if ((this._circuito != value))
				{
					this.OncircuitoChanging(value);
					this.SendPropertyChanging();
					this._circuito = value;
					this.SendPropertyChanged("circuito");
					this.OncircuitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seccion", DbType="NVarChar(50)")]
		public string seccion
		{
			get
			{
				return this._seccion;
			}
			set
			{
				if ((this._seccion != value))
				{
					this.OnseccionChanging(value);
					this.SendPropertyChanging();
					this._seccion = value;
					this.SendPropertyChanged("seccion");
					this.OnseccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecafi", DbType="NVarChar(255)")]
		public string fecafi
		{
			get
			{
				return this._fecafi;
			}
			set
			{
				if ((this._fecafi != value))
				{
					this.OnfecafiChanging(value);
					this.SendPropertyChanging();
					this._fecafi = value;
					this.SendPropertyChanged("fecafi");
					this.OnfecafiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAfil", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAfil
		{
			get
			{
				return this._FechaAfil;
			}
			set
			{
				if ((this._FechaAfil != value))
				{
					this.OnFechaAfilChanging(value);
					this.SendPropertyChanging();
					this._FechaAfil = value;
					this.SendPropertyChanged("FechaAfil");
					this.OnFechaAfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(100)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_calle", DbType="Int")]
		public System.Nullable<int> nro_calle
		{
			get
			{
				return this._nro_calle;
			}
			set
			{
				if ((this._nro_calle != value))
				{
					this.Onnro_calleChanging(value);
					this.SendPropertyChanging();
					this._nro_calle = value;
					this.SendPropertyChanged("nro_calle");
					this.Onnro_calleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partido", DbType="VarChar(50)")]
		public string partido
		{
			get
			{
				return this._partido;
			}
			set
			{
				if ((this._partido != value))
				{
					this.OnpartidoChanging(value);
					this.SendPropertyChanging();
					this._partido = value;
					this.SendPropertyChanged("partido");
					this.OnpartidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuartel", DbType="VarChar(50)")]
		public string cuartel
		{
			get
			{
				return this._cuartel;
			}
			set
			{
				if ((this._cuartel != value))
				{
					this.OncuartelChanging(value);
					this.SendPropertyChanging();
					this._cuartel = value;
					this.SendPropertyChanged("cuartel");
					this.OncuartelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(100)")]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_string2", DbType="VarChar(50)")]
		public string string2
		{
			get
			{
				return this._string2;
			}
			set
			{
				if ((this._string2 != value))
				{
					this.Onstring2Changing(value);
					this.SendPropertyChanging();
					this._string2 = value;
					this.SendPropertyChanged("string2");
					this.Onstring2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia", DbType="VarChar(2)")]
		public string dia
		{
			get
			{
				return this._dia;
			}
			set
			{
				if ((this._dia != value))
				{
					this.OndiaChanging(value);
					this.SendPropertyChanging();
					this._dia = value;
					this.SendPropertyChanged("dia");
					this.OndiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="VarChar(2)")]
		public string mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this.OnmesChanging(value);
					this.SendPropertyChanging();
					this._mes = value;
					this.SendPropertyChanged("mes");
					this.OnmesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_año", DbType="VarChar(4)")]
		public string año
		{
			get
			{
				return this._año;
			}
			set
			{
				if ((this._año != value))
				{
					this.OnañoChanging(value);
					this.SendPropertyChanging();
					this._año = value;
					this.SendPropertyChanged("año");
					this.OnañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadocivil", DbType="VarChar(50)")]
		public string estadocivil
		{
			get
			{
				return this._estadocivil;
			}
			set
			{
				if ((this._estadocivil != value))
				{
					this.OnestadocivilChanging(value);
					this.SendPropertyChanging();
					this._estadocivil = value;
					this.SendPropertyChanged("estadocivil");
					this.OnestadocivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugar", DbType="VarChar(100)")]
		public string lugar
		{
			get
			{
				return this._lugar;
			}
			set
			{
				if ((this._lugar != value))
				{
					this.OnlugarChanging(value);
					this.SendPropertyChanging();
					this._lugar = value;
					this.SendPropertyChanged("lugar");
					this.OnlugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM", DbType="VarChar(10)")]
		public string DM
		{
			get
			{
				return this._DM;
			}
			set
			{
				if ((this._DM != value))
				{
					this.OnDMChanging(value);
					this.SendPropertyChanging();
					this._DM = value;
					this.SendPropertyChanged("DM");
					this.OnDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg", DbType="VarChar(10)")]
		public string reg
		{
			get
			{
				return this._reg;
			}
			set
			{
				if ((this._reg != value))
				{
					this.OnregChanging(value);
					this.SendPropertyChanging();
					this._reg = value;
					this.SendPropertyChanged("reg");
					this.OnregChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piso", DbType="VarChar(5)")]
		public string piso
		{
			get
			{
				return this._piso;
			}
			set
			{
				if ((this._piso != value))
				{
					this.OnpisoChanging(value);
					this.SendPropertyChanging();
					this._piso = value;
					this.SendPropertyChanged("piso");
					this.OnpisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpto", DbType="VarChar(5)")]
		public string dpto
		{
			get
			{
				return this._dpto;
			}
			set
			{
				if ((this._dpto != value))
				{
					this.OndptoChanging(value);
					this.SendPropertyChanging();
					this._dpto = value;
					this.SendPropertyChanged("dpto");
					this.OndptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Padron_Capital")]
	public partial class Padron_Capital
	{
		
		private string _sexo;
		
		private System.Nullable<int> _clase;
		
		private System.Nullable<int> _numdoc;
		
		private string _apenom;
		
		private string _prof;
		
		private string _domicilio;
		
		private string _tipodoc;
		
		private string _analfabeto;
		
		private string _circuito;
		
		private string _seccion;
		
		private string _fecafi;
		
		private System.Nullable<System.DateTime> _FechaAfil;
		
		public Padron_Capital()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="NVarChar(1)")]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clase", DbType="Int")]
		public System.Nullable<int> clase
		{
			get
			{
				return this._clase;
			}
			set
			{
				if ((this._clase != value))
				{
					this._clase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numdoc", DbType="Int")]
		public System.Nullable<int> numdoc
		{
			get
			{
				return this._numdoc;
			}
			set
			{
				if ((this._numdoc != value))
				{
					this._numdoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apenom", DbType="NVarChar(255)")]
		public string apenom
		{
			get
			{
				return this._apenom;
			}
			set
			{
				if ((this._apenom != value))
				{
					this._apenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prof", DbType="NVarChar(50)")]
		public string prof
		{
			get
			{
				return this._prof;
			}
			set
			{
				if ((this._prof != value))
				{
					this._prof = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domicilio", DbType="NVarChar(255)")]
		public string domicilio
		{
			get
			{
				return this._domicilio;
			}
			set
			{
				if ((this._domicilio != value))
				{
					this._domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipodoc", DbType="NVarChar(10)")]
		public string tipodoc
		{
			get
			{
				return this._tipodoc;
			}
			set
			{
				if ((this._tipodoc != value))
				{
					this._tipodoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analfabeto", DbType="NVarChar(50)")]
		public string analfabeto
		{
			get
			{
				return this._analfabeto;
			}
			set
			{
				if ((this._analfabeto != value))
				{
					this._analfabeto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_circuito", DbType="NVarChar(50)")]
		public string circuito
		{
			get
			{
				return this._circuito;
			}
			set
			{
				if ((this._circuito != value))
				{
					this._circuito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seccion", DbType="NVarChar(50)")]
		public string seccion
		{
			get
			{
				return this._seccion;
			}
			set
			{
				if ((this._seccion != value))
				{
					this._seccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecafi", DbType="NVarChar(255)")]
		public string fecafi
		{
			get
			{
				return this._fecafi;
			}
			set
			{
				if ((this._fecafi != value))
				{
					this._fecafi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAfil", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAfil
		{
			get
			{
				return this._FechaAfil;
			}
			set
			{
				if ((this._FechaAfil != value))
				{
					this._FechaAfil = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.maeemp")]
	public partial class maeemp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private double _MAEEMP_CUIT;
		
		private string _MAEEMP_NOMFAN;
		
		private string _MAEEMP_RAZSOC;
		
		private string _MAEEMP_CALLE;
		
		private string _MAEEMP_NRO;
		
		private System.Nullable<char> _MAEEMP_CODPROV;
		
		private System.Nullable<long> _MAEEMP_CODLOC;
		
		private string _MAEEMP_CODPOS;
		
		private string _MAEEMP_TEL;
		
		private string _MAEEMP_EMAIL;
		
		private System.Nullable<long> _MAEEMP_CREDMAX;
		
		private System.Nullable<char> _MAEEMP_CONDCRED;
		
		private System.Nullable<byte> _MAEEMP_ACTUALIZA;
		
		private string _MAEEMP_ESTUDIO_CONTACTO;
		
		private string _MAEEMP_ESTUDIO_TEL;
		
		private string _MAEEMP_ESTUDIO_EMAIL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMAEEMP_CUITChanging(double value);
    partial void OnMAEEMP_CUITChanged();
    partial void OnMAEEMP_NOMFANChanging(string value);
    partial void OnMAEEMP_NOMFANChanged();
    partial void OnMAEEMP_RAZSOCChanging(string value);
    partial void OnMAEEMP_RAZSOCChanged();
    partial void OnMAEEMP_CALLEChanging(string value);
    partial void OnMAEEMP_CALLEChanged();
    partial void OnMAEEMP_NROChanging(string value);
    partial void OnMAEEMP_NROChanged();
    partial void OnMAEEMP_CODPROVChanging(System.Nullable<char> value);
    partial void OnMAEEMP_CODPROVChanged();
    partial void OnMAEEMP_CODLOCChanging(System.Nullable<long> value);
    partial void OnMAEEMP_CODLOCChanged();
    partial void OnMAEEMP_CODPOSChanging(string value);
    partial void OnMAEEMP_CODPOSChanged();
    partial void OnMAEEMP_TELChanging(string value);
    partial void OnMAEEMP_TELChanged();
    partial void OnMAEEMP_EMAILChanging(string value);
    partial void OnMAEEMP_EMAILChanged();
    partial void OnMAEEMP_CREDMAXChanging(System.Nullable<long> value);
    partial void OnMAEEMP_CREDMAXChanged();
    partial void OnMAEEMP_CONDCREDChanging(System.Nullable<char> value);
    partial void OnMAEEMP_CONDCREDChanged();
    partial void OnMAEEMP_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnMAEEMP_ACTUALIZAChanged();
    partial void OnMAEEMP_ESTUDIO_CONTACTOChanging(string value);
    partial void OnMAEEMP_ESTUDIO_CONTACTOChanged();
    partial void OnMAEEMP_ESTUDIO_TELChanging(string value);
    partial void OnMAEEMP_ESTUDIO_TELChanged();
    partial void OnMAEEMP_ESTUDIO_EMAILChanging(string value);
    partial void OnMAEEMP_ESTUDIO_EMAILChanged();
    #endregion
		
		public maeemp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CUIT", DbType="Float NOT NULL")]
		public double MAEEMP_CUIT
		{
			get
			{
				return this._MAEEMP_CUIT;
			}
			set
			{
				if ((this._MAEEMP_CUIT != value))
				{
					this.OnMAEEMP_CUITChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CUIT = value;
					this.SendPropertyChanged("MAEEMP_CUIT");
					this.OnMAEEMP_CUITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_NOMFAN", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_NOMFAN
		{
			get
			{
				return this._MAEEMP_NOMFAN;
			}
			set
			{
				if ((this._MAEEMP_NOMFAN != value))
				{
					this.OnMAEEMP_NOMFANChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_NOMFAN = value;
					this.SendPropertyChanged("MAEEMP_NOMFAN");
					this.OnMAEEMP_NOMFANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_RAZSOC", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_RAZSOC
		{
			get
			{
				return this._MAEEMP_RAZSOC;
			}
			set
			{
				if ((this._MAEEMP_RAZSOC != value))
				{
					this.OnMAEEMP_RAZSOCChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_RAZSOC = value;
					this.SendPropertyChanged("MAEEMP_RAZSOC");
					this.OnMAEEMP_RAZSOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CALLE", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_CALLE
		{
			get
			{
				return this._MAEEMP_CALLE;
			}
			set
			{
				if ((this._MAEEMP_CALLE != value))
				{
					this.OnMAEEMP_CALLEChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CALLE = value;
					this.SendPropertyChanged("MAEEMP_CALLE");
					this.OnMAEEMP_CALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_NRO", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string MAEEMP_NRO
		{
			get
			{
				return this._MAEEMP_NRO;
			}
			set
			{
				if ((this._MAEEMP_NRO != value))
				{
					this.OnMAEEMP_NROChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_NRO = value;
					this.SendPropertyChanged("MAEEMP_NRO");
					this.OnMAEEMP_NROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODPROV", DbType="Char(1)")]
		public System.Nullable<char> MAEEMP_CODPROV
		{
			get
			{
				return this._MAEEMP_CODPROV;
			}
			set
			{
				if ((this._MAEEMP_CODPROV != value))
				{
					this.OnMAEEMP_CODPROVChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODPROV = value;
					this.SendPropertyChanged("MAEEMP_CODPROV");
					this.OnMAEEMP_CODPROVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODLOC", DbType="BigInt")]
		public System.Nullable<long> MAEEMP_CODLOC
		{
			get
			{
				return this._MAEEMP_CODLOC;
			}
			set
			{
				if ((this._MAEEMP_CODLOC != value))
				{
					this.OnMAEEMP_CODLOCChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODLOC = value;
					this.SendPropertyChanged("MAEEMP_CODLOC");
					this.OnMAEEMP_CODLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODPOS", DbType="Char(10)")]
		public string MAEEMP_CODPOS
		{
			get
			{
				return this._MAEEMP_CODPOS;
			}
			set
			{
				if ((this._MAEEMP_CODPOS != value))
				{
					this.OnMAEEMP_CODPOSChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODPOS = value;
					this.SendPropertyChanged("MAEEMP_CODPOS");
					this.OnMAEEMP_CODPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_TEL", DbType="Char(20)")]
		public string MAEEMP_TEL
		{
			get
			{
				return this._MAEEMP_TEL;
			}
			set
			{
				if ((this._MAEEMP_TEL != value))
				{
					this.OnMAEEMP_TELChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_TEL = value;
					this.SendPropertyChanged("MAEEMP_TEL");
					this.OnMAEEMP_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_EMAIL", DbType="Char(40)")]
		public string MAEEMP_EMAIL
		{
			get
			{
				return this._MAEEMP_EMAIL;
			}
			set
			{
				if ((this._MAEEMP_EMAIL != value))
				{
					this.OnMAEEMP_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_EMAIL = value;
					this.SendPropertyChanged("MAEEMP_EMAIL");
					this.OnMAEEMP_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CREDMAX", DbType="BigInt")]
		public System.Nullable<long> MAEEMP_CREDMAX
		{
			get
			{
				return this._MAEEMP_CREDMAX;
			}
			set
			{
				if ((this._MAEEMP_CREDMAX != value))
				{
					this.OnMAEEMP_CREDMAXChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CREDMAX = value;
					this.SendPropertyChanged("MAEEMP_CREDMAX");
					this.OnMAEEMP_CREDMAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CONDCRED", DbType="Char(1)")]
		public System.Nullable<char> MAEEMP_CONDCRED
		{
			get
			{
				return this._MAEEMP_CONDCRED;
			}
			set
			{
				if ((this._MAEEMP_CONDCRED != value))
				{
					this.OnMAEEMP_CONDCREDChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CONDCRED = value;
					this.SendPropertyChanged("MAEEMP_CONDCRED");
					this.OnMAEEMP_CONDCREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> MAEEMP_ACTUALIZA
		{
			get
			{
				return this._MAEEMP_ACTUALIZA;
			}
			set
			{
				if ((this._MAEEMP_ACTUALIZA != value))
				{
					this.OnMAEEMP_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ACTUALIZA = value;
					this.SendPropertyChanged("MAEEMP_ACTUALIZA");
					this.OnMAEEMP_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_CONTACTO", DbType="Char(40)")]
		public string MAEEMP_ESTUDIO_CONTACTO
		{
			get
			{
				return this._MAEEMP_ESTUDIO_CONTACTO;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_CONTACTO != value))
				{
					this.OnMAEEMP_ESTUDIO_CONTACTOChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_CONTACTO = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_CONTACTO");
					this.OnMAEEMP_ESTUDIO_CONTACTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_TEL", DbType="Char(20)")]
		public string MAEEMP_ESTUDIO_TEL
		{
			get
			{
				return this._MAEEMP_ESTUDIO_TEL;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_TEL != value))
				{
					this.OnMAEEMP_ESTUDIO_TELChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_TEL = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_TEL");
					this.OnMAEEMP_ESTUDIO_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_EMAIL", DbType="Char(40)")]
		public string MAEEMP_ESTUDIO_EMAIL
		{
			get
			{
				return this._MAEEMP_ESTUDIO_EMAIL;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_EMAIL != value))
				{
					this.OnMAEEMP_ESTUDIO_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_EMAIL = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_EMAIL");
					this.OnMAEEMP_ESTUDIO_EMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.maesoc")]
	public partial class maesoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private double _MAESOC_CUIL;
		
		private string _MAESOC_APELLIDO;
		
		private string _MAESOC_NOMBRE;
		
		private string _MAESOC_TEL;
		
		private string _MAESOC_TELCEL;
		
		private System.DateTime _MAESOC_FECHANAC;
		
		private short _MAESOC_CARGAFLIA;
		
		private int _MAESOC_JUBIL;
		
		private System.Nullable<byte> _MAESOC_PREDOC;
		
		private System.DateTime _MAESOC_FECHADOC;
		
		private short _MAESOC_CODCAT;
		
		private short _MAESOC_CODACT;
		
		private int _MAESOC_TIPODOC;
		
		private string _MAESOC_NRODOC;
		
		private int _MAESOC_GRUPOSANG;
		
		private char _MAESOC_SEXO;
		
		private char _MAESOC_ESTCIV;
		
		private char _MAESOC_CODPROV;
		
		private int _MAESOC_CODLOC;
		
		private string _MAESOC_CODPOS;
		
		private string _MAESOC_BARRIO;
		
		private string _MAESOC_NACIONALIDAD;
		
		private string _MAESOC_CALLE;
		
		private string _MAESOC_NROCALLE;
		
		private string _MAESOC_PISO;
		
		private string _MAESOC_DTO;
		
		private int _MAESOC_CODOSM;
		
		private System.Nullable<int> _MAESOC_CODCON;
		
		private string _MAESOC_NROAFIL;
		
		private string _MAESOC_EMAIL;
		
		private string _MAESOC_EMAILLAB;
		
		private string _MAESOC_NROCARNET;
		
		private string _MAESOC_IMPEST1;
		
		private string _MAESOC_IMPEST2;
		
		private string _MAESOC_IMPEST3;
		
		private string _MAESOC_IMPEST4;
		
		private string _MAESOC_IMPEST5;
		
		private string _MAESOC_IMPEST6;
		
		private string _MAESOC_DEBAUT_CBU;
		
		private double _MAESOC_DEBAUT_MONTO;
		
		private System.Nullable<byte> _MAESOC_ACTUALIZA;
		
		private System.Nullable<int> _MAESOC_DTOFARMACIA;
		
		private System.DateTime _MAESOC_FECHAALTA;
		
		private System.DateTime _MAESOC_FECHAMOD;
		
		private string _MAESOC_USUMOD;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMAESOC_CUILChanging(double value);
    partial void OnMAESOC_CUILChanged();
    partial void OnMAESOC_APELLIDOChanging(string value);
    partial void OnMAESOC_APELLIDOChanged();
    partial void OnMAESOC_NOMBREChanging(string value);
    partial void OnMAESOC_NOMBREChanged();
    partial void OnMAESOC_TELChanging(string value);
    partial void OnMAESOC_TELChanged();
    partial void OnMAESOC_TELCELChanging(string value);
    partial void OnMAESOC_TELCELChanged();
    partial void OnMAESOC_FECHANACChanging(System.DateTime value);
    partial void OnMAESOC_FECHANACChanged();
    partial void OnMAESOC_CARGAFLIAChanging(short value);
    partial void OnMAESOC_CARGAFLIAChanged();
    partial void OnMAESOC_JUBILChanging(int value);
    partial void OnMAESOC_JUBILChanged();
    partial void OnMAESOC_PREDOCChanging(System.Nullable<byte> value);
    partial void OnMAESOC_PREDOCChanged();
    partial void OnMAESOC_FECHADOCChanging(System.DateTime value);
    partial void OnMAESOC_FECHADOCChanged();
    partial void OnMAESOC_CODCATChanging(short value);
    partial void OnMAESOC_CODCATChanged();
    partial void OnMAESOC_CODACTChanging(short value);
    partial void OnMAESOC_CODACTChanged();
    partial void OnMAESOC_TIPODOCChanging(int value);
    partial void OnMAESOC_TIPODOCChanged();
    partial void OnMAESOC_NRODOCChanging(string value);
    partial void OnMAESOC_NRODOCChanged();
    partial void OnMAESOC_GRUPOSANGChanging(int value);
    partial void OnMAESOC_GRUPOSANGChanged();
    partial void OnMAESOC_SEXOChanging(char value);
    partial void OnMAESOC_SEXOChanged();
    partial void OnMAESOC_ESTCIVChanging(char value);
    partial void OnMAESOC_ESTCIVChanged();
    partial void OnMAESOC_CODPROVChanging(char value);
    partial void OnMAESOC_CODPROVChanged();
    partial void OnMAESOC_CODLOCChanging(int value);
    partial void OnMAESOC_CODLOCChanged();
    partial void OnMAESOC_CODPOSChanging(string value);
    partial void OnMAESOC_CODPOSChanged();
    partial void OnMAESOC_BARRIOChanging(string value);
    partial void OnMAESOC_BARRIOChanged();
    partial void OnMAESOC_NACIONALIDADChanging(string value);
    partial void OnMAESOC_NACIONALIDADChanged();
    partial void OnMAESOC_CALLEChanging(string value);
    partial void OnMAESOC_CALLEChanged();
    partial void OnMAESOC_NROCALLEChanging(string value);
    partial void OnMAESOC_NROCALLEChanged();
    partial void OnMAESOC_PISOChanging(string value);
    partial void OnMAESOC_PISOChanged();
    partial void OnMAESOC_DTOChanging(string value);
    partial void OnMAESOC_DTOChanged();
    partial void OnMAESOC_CODOSMChanging(int value);
    partial void OnMAESOC_CODOSMChanged();
    partial void OnMAESOC_CODCONChanging(System.Nullable<int> value);
    partial void OnMAESOC_CODCONChanged();
    partial void OnMAESOC_NROAFILChanging(string value);
    partial void OnMAESOC_NROAFILChanged();
    partial void OnMAESOC_EMAILChanging(string value);
    partial void OnMAESOC_EMAILChanged();
    partial void OnMAESOC_EMAILLABChanging(string value);
    partial void OnMAESOC_EMAILLABChanged();
    partial void OnMAESOC_NROCARNETChanging(string value);
    partial void OnMAESOC_NROCARNETChanged();
    partial void OnMAESOC_IMPEST1Changing(string value);
    partial void OnMAESOC_IMPEST1Changed();
    partial void OnMAESOC_IMPEST2Changing(string value);
    partial void OnMAESOC_IMPEST2Changed();
    partial void OnMAESOC_IMPEST3Changing(string value);
    partial void OnMAESOC_IMPEST3Changed();
    partial void OnMAESOC_IMPEST4Changing(string value);
    partial void OnMAESOC_IMPEST4Changed();
    partial void OnMAESOC_IMPEST5Changing(string value);
    partial void OnMAESOC_IMPEST5Changed();
    partial void OnMAESOC_IMPEST6Changing(string value);
    partial void OnMAESOC_IMPEST6Changed();
    partial void OnMAESOC_DEBAUT_CBUChanging(string value);
    partial void OnMAESOC_DEBAUT_CBUChanged();
    partial void OnMAESOC_DEBAUT_MONTOChanging(double value);
    partial void OnMAESOC_DEBAUT_MONTOChanged();
    partial void OnMAESOC_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnMAESOC_ACTUALIZAChanged();
    partial void OnMAESOC_DTOFARMACIAChanging(System.Nullable<int> value);
    partial void OnMAESOC_DTOFARMACIAChanged();
    partial void OnMAESOC_FECHAALTAChanging(System.DateTime value);
    partial void OnMAESOC_FECHAALTAChanged();
    partial void OnMAESOC_FECHAMODChanging(System.DateTime value);
    partial void OnMAESOC_FECHAMODChanged();
    partial void OnMAESOC_USUMODChanging(string value);
    partial void OnMAESOC_USUMODChanged();
    #endregion
		
		public maesoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CUIL", DbType="Float NOT NULL")]
		public double MAESOC_CUIL
		{
			get
			{
				return this._MAESOC_CUIL;
			}
			set
			{
				if ((this._MAESOC_CUIL != value))
				{
					this.OnMAESOC_CUILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CUIL = value;
					this.SendPropertyChanged("MAESOC_CUIL");
					this.OnMAESOC_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_APELLIDO", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_APELLIDO
		{
			get
			{
				return this._MAESOC_APELLIDO;
			}
			set
			{
				if ((this._MAESOC_APELLIDO != value))
				{
					this.OnMAESOC_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_APELLIDO = value;
					this.SendPropertyChanged("MAESOC_APELLIDO");
					this.OnMAESOC_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NOMBRE", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_NOMBRE
		{
			get
			{
				return this._MAESOC_NOMBRE;
			}
			set
			{
				if ((this._MAESOC_NOMBRE != value))
				{
					this.OnMAESOC_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NOMBRE = value;
					this.SendPropertyChanged("MAESOC_NOMBRE");
					this.OnMAESOC_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TEL", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MAESOC_TEL
		{
			get
			{
				return this._MAESOC_TEL;
			}
			set
			{
				if ((this._MAESOC_TEL != value))
				{
					this.OnMAESOC_TELChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TEL = value;
					this.SendPropertyChanged("MAESOC_TEL");
					this.OnMAESOC_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TELCEL", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_TELCEL
		{
			get
			{
				return this._MAESOC_TELCEL;
			}
			set
			{
				if ((this._MAESOC_TELCEL != value))
				{
					this.OnMAESOC_TELCELChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TELCEL = value;
					this.SendPropertyChanged("MAESOC_TELCEL");
					this.OnMAESOC_TELCELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHANAC", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHANAC
		{
			get
			{
				return this._MAESOC_FECHANAC;
			}
			set
			{
				if ((this._MAESOC_FECHANAC != value))
				{
					this.OnMAESOC_FECHANACChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHANAC = value;
					this.SendPropertyChanged("MAESOC_FECHANAC");
					this.OnMAESOC_FECHANACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CARGAFLIA", DbType="SmallInt NOT NULL")]
		public short MAESOC_CARGAFLIA
		{
			get
			{
				return this._MAESOC_CARGAFLIA;
			}
			set
			{
				if ((this._MAESOC_CARGAFLIA != value))
				{
					this.OnMAESOC_CARGAFLIAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CARGAFLIA = value;
					this.SendPropertyChanged("MAESOC_CARGAFLIA");
					this.OnMAESOC_CARGAFLIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_JUBIL", DbType="Int NOT NULL")]
		public int MAESOC_JUBIL
		{
			get
			{
				return this._MAESOC_JUBIL;
			}
			set
			{
				if ((this._MAESOC_JUBIL != value))
				{
					this.OnMAESOC_JUBILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_JUBIL = value;
					this.SendPropertyChanged("MAESOC_JUBIL");
					this.OnMAESOC_JUBILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_PREDOC", DbType="TinyInt")]
		public System.Nullable<byte> MAESOC_PREDOC
		{
			get
			{
				return this._MAESOC_PREDOC;
			}
			set
			{
				if ((this._MAESOC_PREDOC != value))
				{
					this.OnMAESOC_PREDOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_PREDOC = value;
					this.SendPropertyChanged("MAESOC_PREDOC");
					this.OnMAESOC_PREDOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHADOC", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHADOC
		{
			get
			{
				return this._MAESOC_FECHADOC;
			}
			set
			{
				if ((this._MAESOC_FECHADOC != value))
				{
					this.OnMAESOC_FECHADOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHADOC = value;
					this.SendPropertyChanged("MAESOC_FECHADOC");
					this.OnMAESOC_FECHADOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODCAT", DbType="SmallInt NOT NULL")]
		public short MAESOC_CODCAT
		{
			get
			{
				return this._MAESOC_CODCAT;
			}
			set
			{
				if ((this._MAESOC_CODCAT != value))
				{
					this.OnMAESOC_CODCATChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODCAT = value;
					this.SendPropertyChanged("MAESOC_CODCAT");
					this.OnMAESOC_CODCATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODACT", DbType="SmallInt NOT NULL")]
		public short MAESOC_CODACT
		{
			get
			{
				return this._MAESOC_CODACT;
			}
			set
			{
				if ((this._MAESOC_CODACT != value))
				{
					this.OnMAESOC_CODACTChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODACT = value;
					this.SendPropertyChanged("MAESOC_CODACT");
					this.OnMAESOC_CODACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TIPODOC", DbType="Int NOT NULL")]
		public int MAESOC_TIPODOC
		{
			get
			{
				return this._MAESOC_TIPODOC;
			}
			set
			{
				if ((this._MAESOC_TIPODOC != value))
				{
					this.OnMAESOC_TIPODOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TIPODOC = value;
					this.SendPropertyChanged("MAESOC_TIPODOC");
					this.OnMAESOC_TIPODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NRODOC", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string MAESOC_NRODOC
		{
			get
			{
				return this._MAESOC_NRODOC;
			}
			set
			{
				if ((this._MAESOC_NRODOC != value))
				{
					this.OnMAESOC_NRODOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NRODOC = value;
					this.SendPropertyChanged("MAESOC_NRODOC");
					this.OnMAESOC_NRODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_GRUPOSANG", DbType="Int NOT NULL")]
		public int MAESOC_GRUPOSANG
		{
			get
			{
				return this._MAESOC_GRUPOSANG;
			}
			set
			{
				if ((this._MAESOC_GRUPOSANG != value))
				{
					this.OnMAESOC_GRUPOSANGChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_GRUPOSANG = value;
					this.SendPropertyChanged("MAESOC_GRUPOSANG");
					this.OnMAESOC_GRUPOSANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_SEXO", DbType="Char(1) NOT NULL")]
		public char MAESOC_SEXO
		{
			get
			{
				return this._MAESOC_SEXO;
			}
			set
			{
				if ((this._MAESOC_SEXO != value))
				{
					this.OnMAESOC_SEXOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_SEXO = value;
					this.SendPropertyChanged("MAESOC_SEXO");
					this.OnMAESOC_SEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_ESTCIV", DbType="Char(1) NOT NULL")]
		public char MAESOC_ESTCIV
		{
			get
			{
				return this._MAESOC_ESTCIV;
			}
			set
			{
				if ((this._MAESOC_ESTCIV != value))
				{
					this.OnMAESOC_ESTCIVChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_ESTCIV = value;
					this.SendPropertyChanged("MAESOC_ESTCIV");
					this.OnMAESOC_ESTCIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODPROV", DbType="Char(1) NOT NULL")]
		public char MAESOC_CODPROV
		{
			get
			{
				return this._MAESOC_CODPROV;
			}
			set
			{
				if ((this._MAESOC_CODPROV != value))
				{
					this.OnMAESOC_CODPROVChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODPROV = value;
					this.SendPropertyChanged("MAESOC_CODPROV");
					this.OnMAESOC_CODPROVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODLOC", DbType="Int NOT NULL")]
		public int MAESOC_CODLOC
		{
			get
			{
				return this._MAESOC_CODLOC;
			}
			set
			{
				if ((this._MAESOC_CODLOC != value))
				{
					this.OnMAESOC_CODLOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODLOC = value;
					this.SendPropertyChanged("MAESOC_CODLOC");
					this.OnMAESOC_CODLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODPOS", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_CODPOS
		{
			get
			{
				return this._MAESOC_CODPOS;
			}
			set
			{
				if ((this._MAESOC_CODPOS != value))
				{
					this.OnMAESOC_CODPOSChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODPOS = value;
					this.SendPropertyChanged("MAESOC_CODPOS");
					this.OnMAESOC_CODPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_BARRIO", DbType="Char(30)")]
		public string MAESOC_BARRIO
		{
			get
			{
				return this._MAESOC_BARRIO;
			}
			set
			{
				if ((this._MAESOC_BARRIO != value))
				{
					this.OnMAESOC_BARRIOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_BARRIO = value;
					this.SendPropertyChanged("MAESOC_BARRIO");
					this.OnMAESOC_BARRIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NACIONALIDAD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_NACIONALIDAD
		{
			get
			{
				return this._MAESOC_NACIONALIDAD;
			}
			set
			{
				if ((this._MAESOC_NACIONALIDAD != value))
				{
					this.OnMAESOC_NACIONALIDADChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NACIONALIDAD = value;
					this.SendPropertyChanged("MAESOC_NACIONALIDAD");
					this.OnMAESOC_NACIONALIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CALLE", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_CALLE
		{
			get
			{
				return this._MAESOC_CALLE;
			}
			set
			{
				if ((this._MAESOC_CALLE != value))
				{
					this.OnMAESOC_CALLEChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CALLE = value;
					this.SendPropertyChanged("MAESOC_CALLE");
					this.OnMAESOC_CALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROCALLE", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROCALLE
		{
			get
			{
				return this._MAESOC_NROCALLE;
			}
			set
			{
				if ((this._MAESOC_NROCALLE != value))
				{
					this.OnMAESOC_NROCALLEChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROCALLE = value;
					this.SendPropertyChanged("MAESOC_NROCALLE");
					this.OnMAESOC_NROCALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_PISO", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_PISO
		{
			get
			{
				return this._MAESOC_PISO;
			}
			set
			{
				if ((this._MAESOC_PISO != value))
				{
					this.OnMAESOC_PISOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_PISO = value;
					this.SendPropertyChanged("MAESOC_PISO");
					this.OnMAESOC_PISOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DTO", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_DTO
		{
			get
			{
				return this._MAESOC_DTO;
			}
			set
			{
				if ((this._MAESOC_DTO != value))
				{
					this.OnMAESOC_DTOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DTO = value;
					this.SendPropertyChanged("MAESOC_DTO");
					this.OnMAESOC_DTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODOSM", DbType="Int NOT NULL")]
		public int MAESOC_CODOSM
		{
			get
			{
				return this._MAESOC_CODOSM;
			}
			set
			{
				if ((this._MAESOC_CODOSM != value))
				{
					this.OnMAESOC_CODOSMChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODOSM = value;
					this.SendPropertyChanged("MAESOC_CODOSM");
					this.OnMAESOC_CODOSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODCON", DbType="Int")]
		public System.Nullable<int> MAESOC_CODCON
		{
			get
			{
				return this._MAESOC_CODCON;
			}
			set
			{
				if ((this._MAESOC_CODCON != value))
				{
					this.OnMAESOC_CODCONChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODCON = value;
					this.SendPropertyChanged("MAESOC_CODCON");
					this.OnMAESOC_CODCONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROAFIL", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROAFIL
		{
			get
			{
				return this._MAESOC_NROAFIL;
			}
			set
			{
				if ((this._MAESOC_NROAFIL != value))
				{
					this.OnMAESOC_NROAFILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROAFIL = value;
					this.SendPropertyChanged("MAESOC_NROAFIL");
					this.OnMAESOC_NROAFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_EMAIL", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAESOC_EMAIL
		{
			get
			{
				return this._MAESOC_EMAIL;
			}
			set
			{
				if ((this._MAESOC_EMAIL != value))
				{
					this.OnMAESOC_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_EMAIL = value;
					this.SendPropertyChanged("MAESOC_EMAIL");
					this.OnMAESOC_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_EMAILLAB", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAESOC_EMAILLAB
		{
			get
			{
				return this._MAESOC_EMAILLAB;
			}
			set
			{
				if ((this._MAESOC_EMAILLAB != value))
				{
					this.OnMAESOC_EMAILLABChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_EMAILLAB = value;
					this.SendPropertyChanged("MAESOC_EMAILLAB");
					this.OnMAESOC_EMAILLABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROCARNET", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROCARNET
		{
			get
			{
				return this._MAESOC_NROCARNET;
			}
			set
			{
				if ((this._MAESOC_NROCARNET != value))
				{
					this.OnMAESOC_NROCARNETChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROCARNET = value;
					this.SendPropertyChanged("MAESOC_NROCARNET");
					this.OnMAESOC_NROCARNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST1", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST1
		{
			get
			{
				return this._MAESOC_IMPEST1;
			}
			set
			{
				if ((this._MAESOC_IMPEST1 != value))
				{
					this.OnMAESOC_IMPEST1Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST1 = value;
					this.SendPropertyChanged("MAESOC_IMPEST1");
					this.OnMAESOC_IMPEST1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST2", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST2
		{
			get
			{
				return this._MAESOC_IMPEST2;
			}
			set
			{
				if ((this._MAESOC_IMPEST2 != value))
				{
					this.OnMAESOC_IMPEST2Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST2 = value;
					this.SendPropertyChanged("MAESOC_IMPEST2");
					this.OnMAESOC_IMPEST2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST3", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST3
		{
			get
			{
				return this._MAESOC_IMPEST3;
			}
			set
			{
				if ((this._MAESOC_IMPEST3 != value))
				{
					this.OnMAESOC_IMPEST3Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST3 = value;
					this.SendPropertyChanged("MAESOC_IMPEST3");
					this.OnMAESOC_IMPEST3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST4", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST4
		{
			get
			{
				return this._MAESOC_IMPEST4;
			}
			set
			{
				if ((this._MAESOC_IMPEST4 != value))
				{
					this.OnMAESOC_IMPEST4Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST4 = value;
					this.SendPropertyChanged("MAESOC_IMPEST4");
					this.OnMAESOC_IMPEST4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST5", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST5
		{
			get
			{
				return this._MAESOC_IMPEST5;
			}
			set
			{
				if ((this._MAESOC_IMPEST5 != value))
				{
					this.OnMAESOC_IMPEST5Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST5 = value;
					this.SendPropertyChanged("MAESOC_IMPEST5");
					this.OnMAESOC_IMPEST5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST6", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST6
		{
			get
			{
				return this._MAESOC_IMPEST6;
			}
			set
			{
				if ((this._MAESOC_IMPEST6 != value))
				{
					this.OnMAESOC_IMPEST6Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST6 = value;
					this.SendPropertyChanged("MAESOC_IMPEST6");
					this.OnMAESOC_IMPEST6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DEBAUT_CBU", DbType="Char(22) NOT NULL", CanBeNull=false)]
		public string MAESOC_DEBAUT_CBU
		{
			get
			{
				return this._MAESOC_DEBAUT_CBU;
			}
			set
			{
				if ((this._MAESOC_DEBAUT_CBU != value))
				{
					this.OnMAESOC_DEBAUT_CBUChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DEBAUT_CBU = value;
					this.SendPropertyChanged("MAESOC_DEBAUT_CBU");
					this.OnMAESOC_DEBAUT_CBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DEBAUT_MONTO", DbType="Float NOT NULL")]
		public double MAESOC_DEBAUT_MONTO
		{
			get
			{
				return this._MAESOC_DEBAUT_MONTO;
			}
			set
			{
				if ((this._MAESOC_DEBAUT_MONTO != value))
				{
					this.OnMAESOC_DEBAUT_MONTOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DEBAUT_MONTO = value;
					this.SendPropertyChanged("MAESOC_DEBAUT_MONTO");
					this.OnMAESOC_DEBAUT_MONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> MAESOC_ACTUALIZA
		{
			get
			{
				return this._MAESOC_ACTUALIZA;
			}
			set
			{
				if ((this._MAESOC_ACTUALIZA != value))
				{
					this.OnMAESOC_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_ACTUALIZA = value;
					this.SendPropertyChanged("MAESOC_ACTUALIZA");
					this.OnMAESOC_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DTOFARMACIA", DbType="Int")]
		public System.Nullable<int> MAESOC_DTOFARMACIA
		{
			get
			{
				return this._MAESOC_DTOFARMACIA;
			}
			set
			{
				if ((this._MAESOC_DTOFARMACIA != value))
				{
					this.OnMAESOC_DTOFARMACIAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DTOFARMACIA = value;
					this.SendPropertyChanged("MAESOC_DTOFARMACIA");
					this.OnMAESOC_DTOFARMACIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHAALTA", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHAALTA
		{
			get
			{
				return this._MAESOC_FECHAALTA;
			}
			set
			{
				if ((this._MAESOC_FECHAALTA != value))
				{
					this.OnMAESOC_FECHAALTAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHAALTA = value;
					this.SendPropertyChanged("MAESOC_FECHAALTA");
					this.OnMAESOC_FECHAALTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHAMOD", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHAMOD
		{
			get
			{
				return this._MAESOC_FECHAMOD;
			}
			set
			{
				if ((this._MAESOC_FECHAMOD != value))
				{
					this.OnMAESOC_FECHAMODChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHAMOD = value;
					this.SendPropertyChanged("MAESOC_FECHAMOD");
					this.OnMAESOC_FECHAMODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_USUMOD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_USUMOD
		{
			get
			{
				return this._MAESOC_USUMOD;
			}
			set
			{
				if ((this._MAESOC_USUMOD != value))
				{
					this.OnMAESOC_USUMODChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_USUMOD = value;
					this.SendPropertyChanged("MAESOC_USUMOD");
					this.OnMAESOC_USUMODChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.soccen")]
	public partial class soccen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private double _SOCCEN_CUIL;
		
		private byte _SOCCEN_ESTADO;
		
		private int _SOCCEN_CODIVA;
		
		private System.Nullable<System.DateTime> _SOCCEN_FEING;
		
		private System.Nullable<System.DateTime> _SOCCEN_FEBAJA;
		
		private int _SOCCEN_NRORESCOMDIR;
		
		private long _SOCCEN_CREDMAX;
		
		private char _SOCCEN_CONDCRED;
		
		private byte _SOCCEN_SOCDIR;
		
		private byte _SOCCEN_DESPEDIDO;
		
		private System.Nullable<byte> _SOCCEN_ACTUALIZA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSOCCEN_CUILChanging(double value);
    partial void OnSOCCEN_CUILChanged();
    partial void OnSOCCEN_ESTADOChanging(byte value);
    partial void OnSOCCEN_ESTADOChanged();
    partial void OnSOCCEN_CODIVAChanging(int value);
    partial void OnSOCCEN_CODIVAChanged();
    partial void OnSOCCEN_FEINGChanging(System.Nullable<System.DateTime> value);
    partial void OnSOCCEN_FEINGChanged();
    partial void OnSOCCEN_FEBAJAChanging(System.Nullable<System.DateTime> value);
    partial void OnSOCCEN_FEBAJAChanged();
    partial void OnSOCCEN_NRORESCOMDIRChanging(int value);
    partial void OnSOCCEN_NRORESCOMDIRChanged();
    partial void OnSOCCEN_CREDMAXChanging(long value);
    partial void OnSOCCEN_CREDMAXChanged();
    partial void OnSOCCEN_CONDCREDChanging(char value);
    partial void OnSOCCEN_CONDCREDChanged();
    partial void OnSOCCEN_SOCDIRChanging(byte value);
    partial void OnSOCCEN_SOCDIRChanged();
    partial void OnSOCCEN_DESPEDIDOChanging(byte value);
    partial void OnSOCCEN_DESPEDIDOChanged();
    partial void OnSOCCEN_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnSOCCEN_ACTUALIZAChanged();
    #endregion
		
		public soccen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CUIL", DbType="Float NOT NULL")]
		public double SOCCEN_CUIL
		{
			get
			{
				return this._SOCCEN_CUIL;
			}
			set
			{
				if ((this._SOCCEN_CUIL != value))
				{
					this.OnSOCCEN_CUILChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CUIL = value;
					this.SendPropertyChanged("SOCCEN_CUIL");
					this.OnSOCCEN_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_ESTADO", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_ESTADO
		{
			get
			{
				return this._SOCCEN_ESTADO;
			}
			set
			{
				if ((this._SOCCEN_ESTADO != value))
				{
					this.OnSOCCEN_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_ESTADO = value;
					this.SendPropertyChanged("SOCCEN_ESTADO");
					this.OnSOCCEN_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CODIVA", DbType="Int NOT NULL")]
		public int SOCCEN_CODIVA
		{
			get
			{
				return this._SOCCEN_CODIVA;
			}
			set
			{
				if ((this._SOCCEN_CODIVA != value))
				{
					this.OnSOCCEN_CODIVAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CODIVA = value;
					this.SendPropertyChanged("SOCCEN_CODIVA");
					this.OnSOCCEN_CODIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_FEING", DbType="Date")]
		public System.Nullable<System.DateTime> SOCCEN_FEING
		{
			get
			{
				return this._SOCCEN_FEING;
			}
			set
			{
				if ((this._SOCCEN_FEING != value))
				{
					this.OnSOCCEN_FEINGChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_FEING = value;
					this.SendPropertyChanged("SOCCEN_FEING");
					this.OnSOCCEN_FEINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_FEBAJA", DbType="Date")]
		public System.Nullable<System.DateTime> SOCCEN_FEBAJA
		{
			get
			{
				return this._SOCCEN_FEBAJA;
			}
			set
			{
				if ((this._SOCCEN_FEBAJA != value))
				{
					this.OnSOCCEN_FEBAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_FEBAJA = value;
					this.SendPropertyChanged("SOCCEN_FEBAJA");
					this.OnSOCCEN_FEBAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_NRORESCOMDIR", DbType="Int NOT NULL")]
		public int SOCCEN_NRORESCOMDIR
		{
			get
			{
				return this._SOCCEN_NRORESCOMDIR;
			}
			set
			{
				if ((this._SOCCEN_NRORESCOMDIR != value))
				{
					this.OnSOCCEN_NRORESCOMDIRChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_NRORESCOMDIR = value;
					this.SendPropertyChanged("SOCCEN_NRORESCOMDIR");
					this.OnSOCCEN_NRORESCOMDIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CREDMAX", DbType="BigInt NOT NULL")]
		public long SOCCEN_CREDMAX
		{
			get
			{
				return this._SOCCEN_CREDMAX;
			}
			set
			{
				if ((this._SOCCEN_CREDMAX != value))
				{
					this.OnSOCCEN_CREDMAXChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CREDMAX = value;
					this.SendPropertyChanged("SOCCEN_CREDMAX");
					this.OnSOCCEN_CREDMAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CONDCRED", DbType="Char(1) NOT NULL")]
		public char SOCCEN_CONDCRED
		{
			get
			{
				return this._SOCCEN_CONDCRED;
			}
			set
			{
				if ((this._SOCCEN_CONDCRED != value))
				{
					this.OnSOCCEN_CONDCREDChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CONDCRED = value;
					this.SendPropertyChanged("SOCCEN_CONDCRED");
					this.OnSOCCEN_CONDCREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_SOCDIR", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_SOCDIR
		{
			get
			{
				return this._SOCCEN_SOCDIR;
			}
			set
			{
				if ((this._SOCCEN_SOCDIR != value))
				{
					this.OnSOCCEN_SOCDIRChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_SOCDIR = value;
					this.SendPropertyChanged("SOCCEN_SOCDIR");
					this.OnSOCCEN_SOCDIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_DESPEDIDO", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_DESPEDIDO
		{
			get
			{
				return this._SOCCEN_DESPEDIDO;
			}
			set
			{
				if ((this._SOCCEN_DESPEDIDO != value))
				{
					this.OnSOCCEN_DESPEDIDOChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_DESPEDIDO = value;
					this.SendPropertyChanged("SOCCEN_DESPEDIDO");
					this.OnSOCCEN_DESPEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> SOCCEN_ACTUALIZA
		{
			get
			{
				return this._SOCCEN_ACTUALIZA;
			}
			set
			{
				if ((this._SOCCEN_ACTUALIZA != value))
				{
					this.OnSOCCEN_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_ACTUALIZA = value;
					this.SendPropertyChanged("SOCCEN_ACTUALIZA");
					this.OnSOCCEN_ACTUALIZAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.socemp")]
	public partial class socemp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private double _SOCEMP_CUIL;
		
		private double _SOCEMP_CUITE;
		
		private byte _SOCEMP_ESTADO;
		
		private System.DateTime _SOCEMP_FECHAING;
		
		private System.DateTime _SOCEMP_FECHABAJA;
		
		private char _SOCEMP_CAUSABAJA;
		
		private string _SOCEMP_NROLEG;
		
		private byte _SOCEMP_SOCIOCENTRO;
		
		private char _SOCEMP_ULT_EMPRESA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSOCEMP_CUILChanging(double value);
    partial void OnSOCEMP_CUILChanged();
    partial void OnSOCEMP_CUITEChanging(double value);
    partial void OnSOCEMP_CUITEChanged();
    partial void OnSOCEMP_ESTADOChanging(byte value);
    partial void OnSOCEMP_ESTADOChanged();
    partial void OnSOCEMP_FECHAINGChanging(System.DateTime value);
    partial void OnSOCEMP_FECHAINGChanged();
    partial void OnSOCEMP_FECHABAJAChanging(System.DateTime value);
    partial void OnSOCEMP_FECHABAJAChanged();
    partial void OnSOCEMP_CAUSABAJAChanging(char value);
    partial void OnSOCEMP_CAUSABAJAChanged();
    partial void OnSOCEMP_NROLEGChanging(string value);
    partial void OnSOCEMP_NROLEGChanged();
    partial void OnSOCEMP_SOCIOCENTROChanging(byte value);
    partial void OnSOCEMP_SOCIOCENTROChanged();
    partial void OnSOCEMP_ULT_EMPRESAChanging(char value);
    partial void OnSOCEMP_ULT_EMPRESAChanged();
    #endregion
		
		public socemp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CUIL", DbType="Float NOT NULL")]
		public double SOCEMP_CUIL
		{
			get
			{
				return this._SOCEMP_CUIL;
			}
			set
			{
				if ((this._SOCEMP_CUIL != value))
				{
					this.OnSOCEMP_CUILChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CUIL = value;
					this.SendPropertyChanged("SOCEMP_CUIL");
					this.OnSOCEMP_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CUITE", DbType="Float NOT NULL")]
		public double SOCEMP_CUITE
		{
			get
			{
				return this._SOCEMP_CUITE;
			}
			set
			{
				if ((this._SOCEMP_CUITE != value))
				{
					this.OnSOCEMP_CUITEChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CUITE = value;
					this.SendPropertyChanged("SOCEMP_CUITE");
					this.OnSOCEMP_CUITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_ESTADO", DbType="TinyInt NOT NULL")]
		public byte SOCEMP_ESTADO
		{
			get
			{
				return this._SOCEMP_ESTADO;
			}
			set
			{
				if ((this._SOCEMP_ESTADO != value))
				{
					this.OnSOCEMP_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_ESTADO = value;
					this.SendPropertyChanged("SOCEMP_ESTADO");
					this.OnSOCEMP_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_FECHAING", DbType="Date NOT NULL")]
		public System.DateTime SOCEMP_FECHAING
		{
			get
			{
				return this._SOCEMP_FECHAING;
			}
			set
			{
				if ((this._SOCEMP_FECHAING != value))
				{
					this.OnSOCEMP_FECHAINGChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_FECHAING = value;
					this.SendPropertyChanged("SOCEMP_FECHAING");
					this.OnSOCEMP_FECHAINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_FECHABAJA", DbType="Date NOT NULL")]
		public System.DateTime SOCEMP_FECHABAJA
		{
			get
			{
				return this._SOCEMP_FECHABAJA;
			}
			set
			{
				if ((this._SOCEMP_FECHABAJA != value))
				{
					this.OnSOCEMP_FECHABAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_FECHABAJA = value;
					this.SendPropertyChanged("SOCEMP_FECHABAJA");
					this.OnSOCEMP_FECHABAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CAUSABAJA", DbType="Char(1) NOT NULL")]
		public char SOCEMP_CAUSABAJA
		{
			get
			{
				return this._SOCEMP_CAUSABAJA;
			}
			set
			{
				if ((this._SOCEMP_CAUSABAJA != value))
				{
					this.OnSOCEMP_CAUSABAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CAUSABAJA = value;
					this.SendPropertyChanged("SOCEMP_CAUSABAJA");
					this.OnSOCEMP_CAUSABAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_NROLEG", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string SOCEMP_NROLEG
		{
			get
			{
				return this._SOCEMP_NROLEG;
			}
			set
			{
				if ((this._SOCEMP_NROLEG != value))
				{
					this.OnSOCEMP_NROLEGChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_NROLEG = value;
					this.SendPropertyChanged("SOCEMP_NROLEG");
					this.OnSOCEMP_NROLEGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_SOCIOCENTRO", DbType="TinyInt NOT NULL")]
		public byte SOCEMP_SOCIOCENTRO
		{
			get
			{
				return this._SOCEMP_SOCIOCENTRO;
			}
			set
			{
				if ((this._SOCEMP_SOCIOCENTRO != value))
				{
					this.OnSOCEMP_SOCIOCENTROChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_SOCIOCENTRO = value;
					this.SendPropertyChanged("SOCEMP_SOCIOCENTRO");
					this.OnSOCEMP_SOCIOCENTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_ULT_EMPRESA", DbType="Char(1) NOT NULL")]
		public char SOCEMP_ULT_EMPRESA
		{
			get
			{
				return this._SOCEMP_ULT_EMPRESA;
			}
			set
			{
				if ((this._SOCEMP_ULT_EMPRESA != value))
				{
					this.OnSOCEMP_ULT_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_ULT_EMPRESA = value;
					this.SendPropertyChanged("SOCEMP_ULT_EMPRESA");
					this.OnSOCEMP_ULT_EMPRESAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Capital")]
	public partial class Capital
	{
		
		private System.Nullable<double> _DOC;
		
		private System.Nullable<double> _CLASE;
		
		private string _APELLIDO;
		
		private string _NOMBRE;
		
		private string _DOMICILIO;
		
		private string _TIPODOC;
		
		private System.Nullable<double> _SECCION;
		
		private string _CIRCUITO;
		
		private System.Nullable<double> _MESA;
		
		private string _SEXO;
		
		private System.Nullable<double> _ORDEN;
		
		public Capital()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC", DbType="Float")]
		public System.Nullable<double> DOC
		{
			get
			{
				return this._DOC;
			}
			set
			{
				if ((this._DOC != value))
				{
					this._DOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASE", DbType="Float")]
		public System.Nullable<double> CLASE
		{
			get
			{
				return this._CLASE;
			}
			set
			{
				if ((this._CLASE != value))
				{
					this._CLASE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="NVarChar(255)")]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this._APELLIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(255)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="NVarChar(255)")]
		public string DOMICILIO
		{
			get
			{
				return this._DOMICILIO;
			}
			set
			{
				if ((this._DOMICILIO != value))
				{
					this._DOMICILIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPODOC", DbType="NVarChar(255)")]
		public string TIPODOC
		{
			get
			{
				return this._TIPODOC;
			}
			set
			{
				if ((this._TIPODOC != value))
				{
					this._TIPODOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECCION", DbType="Float")]
		public System.Nullable<double> SECCION
		{
			get
			{
				return this._SECCION;
			}
			set
			{
				if ((this._SECCION != value))
				{
					this._SECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIRCUITO", DbType="NVarChar(255)")]
		public string CIRCUITO
		{
			get
			{
				return this._CIRCUITO;
			}
			set
			{
				if ((this._CIRCUITO != value))
				{
					this._CIRCUITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESA", DbType="Float")]
		public System.Nullable<double> MESA
		{
			get
			{
				return this._MESA;
			}
			set
			{
				if ((this._MESA != value))
				{
					this._MESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEXO", DbType="NVarChar(255)")]
		public string SEXO
		{
			get
			{
				return this._SEXO;
			}
			set
			{
				if ((this._SEXO != value))
				{
					this._SEXO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDEN", DbType="Float")]
		public System.Nullable<double> ORDEN
		{
			get
			{
				return this._ORDEN;
			}
			set
			{
				if ((this._ORDEN != value))
				{
					this._ORDEN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pettazi")]
	public partial class pettazi
	{
		
		private string _Apellido_y_Nombre__asc_;
		
		private string _Legajo;
		
		private string _Fecha;
		
		private string _Turno;
		
		private string _Entrada;
		
		private string _Salida;
		
		private string _Marca_Entrada;
		
		private string _Marca_Salida;
		
		private string _Horas_Asignadas;
		
		private string _Horas_Normales;
		
		private System.Nullable<System.DateTime> _HorasExtras;
		
		private string _Total_Horas;
		
		private string _Fichadora;
		
		private string _Ubicación;
		
		public pettazi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apellido y Nombre (asc)]", Storage="_Apellido_y_Nombre__asc_", DbType="NVarChar(255)")]
		public string Apellido_y_Nombre__asc_
		{
			get
			{
				return this._Apellido_y_Nombre__asc_;
			}
			set
			{
				if ((this._Apellido_y_Nombre__asc_ != value))
				{
					this._Apellido_y_Nombre__asc_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Legajo", DbType="NVarChar(255)")]
		public string Legajo
		{
			get
			{
				return this._Legajo;
			}
			set
			{
				if ((this._Legajo != value))
				{
					this._Legajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(255)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="NVarChar(255)")]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this._Turno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="NVarChar(255)")]
		public string Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this._Entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salida", DbType="NVarChar(255)")]
		public string Salida
		{
			get
			{
				return this._Salida;
			}
			set
			{
				if ((this._Salida != value))
				{
					this._Salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marca Entrada]", Storage="_Marca_Entrada", DbType="NVarChar(255)")]
		public string Marca_Entrada
		{
			get
			{
				return this._Marca_Entrada;
			}
			set
			{
				if ((this._Marca_Entrada != value))
				{
					this._Marca_Entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marca Salida]", Storage="_Marca_Salida", DbType="NVarChar(255)")]
		public string Marca_Salida
		{
			get
			{
				return this._Marca_Salida;
			}
			set
			{
				if ((this._Marca_Salida != value))
				{
					this._Marca_Salida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Horas Asignadas]", Storage="_Horas_Asignadas", DbType="NVarChar(255)")]
		public string Horas_Asignadas
		{
			get
			{
				return this._Horas_Asignadas;
			}
			set
			{
				if ((this._Horas_Asignadas != value))
				{
					this._Horas_Asignadas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Horas Normales]", Storage="_Horas_Normales", DbType="NVarChar(255)")]
		public string Horas_Normales
		{
			get
			{
				return this._Horas_Normales;
			}
			set
			{
				if ((this._Horas_Normales != value))
				{
					this._Horas_Normales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorasExtras", DbType="DateTime")]
		public System.Nullable<System.DateTime> HorasExtras
		{
			get
			{
				return this._HorasExtras;
			}
			set
			{
				if ((this._HorasExtras != value))
				{
					this._HorasExtras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Horas]", Storage="_Total_Horas", DbType="NVarChar(255)")]
		public string Total_Horas
		{
			get
			{
				return this._Total_Horas;
			}
			set
			{
				if ((this._Total_Horas != value))
				{
					this._Total_Horas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fichadora", DbType="NVarChar(255)")]
		public string Fichadora
		{
			get
			{
				return this._Fichadora;
			}
			set
			{
				if ((this._Fichadora != value))
				{
					this._Fichadora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="NVarChar(255)")]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this._Ubicación = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
